function [est_pos_cm, total_error_cm, result] = tdoa_localization_2d()
%TDOA_LOCALIZATION_2D 以 TOA 進行二維 TDOA 定位。
% 座標輸入與輸出為 cm；內部計算為 m；TOA 為 s。
% 三顆感測器使用原點初始值；四顆以上使用 Linear LS 初始值。

    clc;
    close all;
    sensor_pos_cm = [
       100,  0;     % Sensor 1
        60,  0;     % Sensor 2
        20,  0;     % Sensor 3
         0, 20;     % Sensor 4
         0, 60;     % Sensor 5
         0,100
    ];
    sensor_count = size(sensor_pos_cm, 1);
    sensor_pos_m = sensor_pos_cm / 100;
    fprintf('\n');
    fprintf('========== 固定感測頭配置 ==========\n');
    for i = 1:sensor_count
        fprintf( ...
            'Sensor %d：x = %.1f cm，y = %.1f cm\n', ...
            i, ...
            sensor_pos_cm(i,1), ...
            sensor_pos_cm(i,2) ...
        );
    end
    sensor_geometry_rank = rank( ...
        [ ...
            sensor_pos_m, ...
            ones(sensor_count,1) ...
        ] ...
    );
    if sensor_geometry_rank < 3
        error( ...
            'TDOA:CollinearSensors', ...
            ['感測頭不可全部位於同一直線上，' ...
             '否則無法進行可靠的 2D TDOA 定位。'] ...
        );
    end
    c = 349;
    true_pos_cm = input( ...
        '\n請輸入聲源真實位置 [x y] (cm): ' ...
    );
    validateattributes( ...
        true_pos_cm, ...
        {'numeric'}, ...
        { ...
            'real', ...
            'finite', ...
            'vector', ...
            'numel', 2 ...
        }, ...
        mfilename, ...
        'true_pos_cm' ...
    );
    true_pos_cm = true_pos_cm(:);
 arrival_times = [
    2.91020;    % Sensor 1
    2.90926;    % Sensor 2
    2.90840;    % Sensor 3
    2.90760;    % Sensor 4
    2.90676;    % Sensor 5
    2.90654     % Sensor 6
];
    if numel(arrival_times) ~= sensor_count
        error( ...
            '抵達時間數量與感測頭數量不一致。' ...
        );
    end
    arrival_times = arrival_times(:);
    fprintf('\n');
    fprintf('========== 固定抵達時間 ==========\n');
    for i = 1:sensor_count
        fprintf( ...
            'Sensor %d / Pair %d：%.5f s\n', ...
            i, ...
            i, ...
            arrival_times(i) ...
        );
    end
    [~, ref_idx] = min(arrival_times);
    fprintf( ...
        '\n最先收到訊號的感測頭為 #%d（Reference Sensor）\n', ...
        ref_idx ...
    );
    ref_sensor_pos_cm = ...
        sensor_pos_cm(ref_idx,:).';
    fprintf( ...
        'Reference Sensor 座標：(%.1f, %.1f) cm\n', ...
        ref_sensor_pos_cm(1), ...
        ref_sensor_pos_cm(2) ...
    );
    sensor_indices = 1:sensor_count;
    sensor_indices(ref_idx) = [];

    % rho_i = d_i - d_ref，單位 m。
    rho = c * ( ...
        arrival_times(sensor_indices) ...
        - arrival_times(ref_idx) ...
    );
    rho = rho(:);
    if sensor_count == 3
        p0 = [
            0;
            0
        ];
        initialization_method = ...
            'Origin initial guess + LM';
        u_ls = nan(3,1);
        rank_A = NaN;
        A_ls = [];
        b_ls = [];
        fprintf('\n');
        fprintf('三顆感測頭定位模式：\n');
        fprintf('跳過 Linear LS。\n');
        fprintf( ...
            'LM 初始位置：x = %.3f cm，y = %.3f cm\n', ...
            p0(1)*100, ...
            p0(2)*100 ...
        );
    else
        [ ...
            p0, ...
            u_ls, ...
            rank_A, ...
            A_ls, ...
            b_ls ...
        ] = ...
            tdoa_linear_ls_initial_2d( ...
                sensor_pos_m, ...
                rho, ...
                ref_idx ...
            );
        if rank_A < 3 || any(~isfinite(p0))
            error( ...
                'TDOA:DegenerateLinearSystem', ...
                ['Linear LS 無法唯一求解 [x,y,r_ref]。' ...
                 '請檢查感測頭幾何配置或抵達時間。'] ...
            );
        end
        initialization_method = ...
            'Linear LS + LM';
        fprintf('\n');
        fprintf('四顆以上感測頭定位模式：\n');
        fprintf('Linear LS -> LM\n');
        fprintf( ...
            'LS 初始位置：x = %.3f cm，y = %.3f cm\n', ...
            p0(1)*100, ...
            p0(2)*100 ...
        );
        fprintf( ...
            'LS 矩陣 rank(A) = %d\n', ...
            rank_A ...
        );
    end
    options = optimoptions( ...
        'lsqnonlin', ...
        'Display', 'none', ...
        'Algorithm', 'levenberg-marquardt', ...
        'MaxIterations', 100, ...
        'MaxFunctionEvaluations', 500, ...
        'FunctionTolerance', 1e-12, ...
        'StepTolerance', 1e-12, ...
        'OptimalityTolerance', 1e-12 ...
    );
    [ ...
        est_pos_m, ...
        resnorm, ...
        residual, ...
        exitflag, ...
        output ...
    ] = ...
        lsqnonlin( ...
            @(p) ...
            tdoa_residuals_2d( ...
                p, ...
                sensor_pos_m, ...
                rho, ...
                ref_idx ...
            ), ...
            p0, ...
            [], ...
            [], ...
            options ...
        );
    est_pos_m = est_pos_m(:);
    est_pos_cm = ...
        est_pos_m * 100;
    error_vec_cm = ...
        est_pos_cm ...
        - true_pos_cm;
    total_error_cm = ...
        norm(error_vec_cm);
    true_source_to_ref_cm = ...
        norm(true_pos_cm - ref_sensor_pos_cm);
    true_source_to_sensor_distance_cm = sqrt( ...
        sum( ...
        (sensor_pos_cm - true_pos_cm.').^2, ...
        2 ...
        ) ...
        );
    max_sensor_distance_cm = ...
        max(true_source_to_sensor_distance_cm);
    percent_ref_sensor_idx = find( ...
        abs(true_source_to_sensor_distance_cm - max_sensor_distance_cm) < 1e-10, ...
        1, ...
        'first' ...
        );
    percent_reference_distance_cm = ...
        true_source_to_sensor_distance_cm(percent_ref_sensor_idx);

    % 相對誤差以真實聲源到最遠感測器的距離為分母。
    if percent_reference_distance_cm > 1e-12
    error_percent = ...
        total_error_cm ...
        / percent_reference_distance_cm ...
        * 100;
    else
        error_percent = NaN;
    end
    estimated_source_to_ref_cm = ...
        norm( ...
            est_pos_cm ...
            - ref_sensor_pos_cm ...
        );
    estimated_rho = ...
        calculate_tdoa_distance_difference( ...
            est_pos_m, ...
            sensor_pos_m, ...
            ref_idx ...
        );
    rho_error = ...
        estimated_rho ...
        - rho;
    result.sensor_count = ...
        sensor_count;
    result.sensor_positions_cm = ...
        sensor_pos_cm;
    result.reference_sensor = ...
        ref_idx;
    result.reference_sensor_position_cm = ...
        ref_sensor_pos_cm;
    result.sound_speed_mps = ...
        c;
    result.arrival_times_s = ...
        arrival_times;
    result.rho_m = ...
        rho;
    result.initialization_method = ...
        initialization_method;
    result.initial_position_cm = ...
        p0 * 100;
    result.ls_used = ...
        sensor_count >= 4;
    result.ls_rank = ...
        rank_A;
    result.ls_state = ...
        u_ls;
    result.ls_matrix_A = ...
        A_ls;
    result.ls_vector_b = ...
        b_ls;
    if sensor_count >= 4
        result.ls_position_cm = ...
            p0 * 100;
    else
        result.ls_position_cm = ...
            [NaN; NaN];
    end
    result.lm_position_cm = ...
        est_pos_cm;
    result.lm_residual_m = ...
        residual;
    result.lm_resnorm_m2 = ...
        resnorm;
    result.lm_exitflag = ...
        exitflag;
    result.lm_output = ...
        output;
    result.estimated_rho_m = ...
        estimated_rho;
    result.rho_error_m = ...
        rho_error;
    result.true_position_cm = ...
        true_pos_cm;
    result.error_vector_cm = ...
        error_vec_cm;
    result.total_error_cm = ...
        total_error_cm;
    result.true_source_to_reference_distance_cm = ...
        true_source_to_ref_cm;
    result.estimated_source_to_reference_distance_cm = ...
        estimated_source_to_ref_cm;
    result.error_percent = ...
        error_percent;
    fprintf('\n');
    fprintf('============================================\n');
    fprintf('                定位結果\n');
    fprintf('============================================\n');
    fprintf( ...
        '感測頭數量                  : %d\n', ...
        sensor_count ...
    );
    fprintf( ...
        'Reference Sensor         : #%d\n', ...
        ref_idx ...
    );
    fprintf( ...
        '定位方法                  : %s\n', ...
        initialization_method ...
    );
    if sensor_count == 3
        fprintf( ...
            'LM 初始位置 (cm)        : x = %.3f, y = %.3f\n', ...
            p0(1)*100, ...
            p0(2)*100 ...
        );
    else
        fprintf( ...
            'LS 初始位置 (cm)        : x = %.3f, y = %.3f\n', ...
            p0(1)*100, ...
            p0(2)*100 ...
        );
        fprintf( ...
            'LS rank(A)              : %d\n', ...
            rank_A ...
        );
    end
    fprintf( ...
        'LM 估計位置 (cm)          : x = %.3f, y = %.3f\n', ...
        est_pos_cm(1), ...
        est_pos_cm(2) ...
    );
    fprintf( ...
        '真實位置 (cm)             : x = %.3f, y = %.3f\n', ...
        true_pos_cm(1), ...
        true_pos_cm(2) ...
    );
    fprintf( ...
        'x 軸誤差 (cm)             : %.3f\n', ...
        error_vec_cm(1) ...
    );
    fprintf( ...
        'y 軸誤差 (cm)             : %.3f\n', ...
        error_vec_cm(2) ...
    );
    fprintf( ...
        '總定位誤差 (cm)           : %.3f (%.2f%%)\n', ...
        total_error_cm, ...
        error_percent ...
    );
    fprintf( ...
        '真實 Source -> Ref (cm)   : %.3f\n', ...
        true_source_to_ref_cm ...
    );
    fprintf( ...
        '估計 Source -> Ref (cm)   : %.3f\n', ...
        estimated_source_to_ref_cm ...
    );
    fprintf( ...
        'LM residual sum of squares          : %.6e m^2\n', ...
        resnorm ...
    );
    fprintf( ...
        'LM exitflag               : %d\n', ...
        exitflag ...
    );
    fprintf( ...
        'LM 迭代次數               : %d\n', ...
        output.iterations ...
    );
    fprintf('\n');
    fprintf('========== TDOA 距離差殘差 ==========\n');
    for n = 1:numel(sensor_indices)
        fprintf( ...
            ['Sensor #%d 相對 Sensor #%d：' ...
             '量測 rho = %.6f m，' ...
             '估計 rho = %.6f m，' ...
             '差值 = %.6e m\n'], ...
            sensor_indices(n), ...
            ref_idx, ...
            rho(n), ...
            estimated_rho(n), ...
            rho_error(n) ...
        );
    end
    fig = figure( ...
        'Color', 'w', ...
        'Position', [100, 100, 1200, 550], ...
        'Name', '2D TDOA Localization' ...
    );
    ax1 = subplot(1,2,1);
    hold(ax1, 'on');
    grid(ax1, 'on');
    box(ax1, 'on');
    axis(ax1, 'equal');
    set(ax1, ...
        'Color', 'w', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'GridColor', [0.5 0.5 0.5], ...
        'MinorGridColor', [0.9 0.9 0.9]);
    scatter( ...
        sensor_pos_cm(:,1), ...
        sensor_pos_cm(:,2), ...
        180, ...
        'bo', ...
        'filled', ...
        'DisplayName', '感測頭' ...
    );
    label_offset_x = 0;
    label_offset_y = 3;   % 往上移 3 cm，可自行調整
    for i = 1:sensor_count
        if i == ref_idx
            sensor_label = sprintf('%dR', i);
        else
            sensor_label = sprintf('%d', i);
        end
        text( ...
            sensor_pos_cm(i,1) + label_offset_x, ...
            sensor_pos_cm(i,2) + label_offset_y, ...
            sensor_label, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 15, ...
            'FontWeight', 'bold', ...
            'Color', 'k',...
            'Margin', 1 ...
        );
    end
    scatter( ...
        true_pos_cm(1), ...
        true_pos_cm(2), ...
        180, ...
        'ro', ...
        'filled', ...
        'DisplayName', '真實位置' ...
    );
    scatter( ...
        est_pos_cm(1), ...
        est_pos_cm(2), ...
        180, ...
        'k^', ...
        'filled', ...
        'DisplayName', 'LM 估計位置' ...
    );
    text( ...
        est_pos_cm(1) + 3, ...
        est_pos_cm(2), ...
        sprintf('(%.1f, %.1f)', est_pos_cm(1), est_pos_cm(2)), ...
        'FontSize', 15, ...
        'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle' ...
        );
    xlabel( ...
        'x (cm)', ...
        'FontSize', 15, ...
        'Color', 'k' ...
    );
    ylabel( ...
        'y (cm)', ...
        'FontSize', 15, ...
        'Color', 'k' ...
    );
    if sensor_count == 3
        title( ...
            '2D TDOA：LM 定位（三顆感測頭）', ...
            'FontSize', 15, ...
            'FontWeight', 'bold', ...
            'Color', 'k' ...
        );
    else
        title( ...
            sprintf( ...
                '2D TDOA：LS + LM（%d 顆感測頭）', ...
                sensor_count ...
            ), ...
            'FontSize', 15, ...
            'FontWeight', 'bold', ...
            'Color', 'k' ...
        );
    end
    legend( ...
        'Location', 'best', ...
        'FontSize', 15, ...
        'TextColor', 'k', ...
        'Color', 'w', ...
        'EdgeColor', 'k' ...
    );
    set(ax1, 'FontSize', 15);
    hold(ax1, 'off');
    ax2 = subplot(1,2,2);
    bar(error_vec_cm);
    grid(ax2, 'on');
    box(ax2, 'on');
    max_abs_error = max(abs(error_vec_cm));
    if max_abs_error <= 10
        y_limit = 10;
    else
        y_limit = 5 * ceil(max_abs_error / 5);
    end
    ylim(ax2, [-y_limit, y_limit]);
    set(ax2, ...
        'Color', 'w', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'GridColor', [0.5 0.5 0.5], ...
        'MinorGridColor', [0.9 0.9 0.9]);
    ylabel( ...
        '誤差 (cm)', ...
        'FontSize', 15, ...
        'Color', 'k' ...
    );
    xticks(1:2);
    xticklabels({ ...
        'x 軸', ...
        'y 軸' ...
    });
    title( ...
        sprintf( ...
            '定位誤差：總誤差 %.3f cm (%.2f%%)', ...
            total_error_cm, ...
            error_percent ...
        ), ...
        'FontSize', 15, ...
        'FontWeight', 'bold', ...
        'Color', 'k' ...
    );
    set(ax2, 'FontSize', 15);
    set( ...
        findall( ...
            gcf, ...
            '-property', ...
            'FontSize' ...
        ), ...
        'FontSize', 15 ...
    );
end

function [p0, u, rank_A, A, b] = ...
    tdoa_linear_ls_initial_2d( ...
        sensors, ...
        rho, ...
        ref_idx ...
    )
    sensor_indices = ...
        1:size(sensors,1);
    sensor_indices(ref_idx) = [];
    ref = ...
        sensors(ref_idx,:);
    num_equations = ...
        numel(sensor_indices);
    A = ...
        zeros(num_equations,3);
    b = ...
        zeros(num_equations,1);
    for n = 1:num_equations
        i = ...
            sensor_indices(n);
        rho_i = ...
            rho(n);
        A(n,:) = [
            2 * (ref(1) - sensors(i,1)), ...
            2 * (ref(2) - sensors(i,2)), ...
            -2 * rho_i
        ];
        b(n) = ...
            ref(1)^2 ...
            + ref(2)^2 ...
            - sensors(i,1)^2 ...
            - sensors(i,2)^2 ...
            + rho_i^2;
    end
    rank_A = ...
        rank(A);
    if rank_A < 3
        p0 = [
            NaN;
            NaN
        ];
        u = ...
            nan(3,1);
        return;
    end
    u = ...
        A \ b;
    p0 = ...
        u(1:2);
    p0 = ...
        p0(:);
end

% 殘差 e_i(p) = ||p-s_i|| - ||p-s_ref|| - rho_i。
function residual = ...
    tdoa_residuals_2d( ...
        p, ...
        sensors, ...
        rho, ...
        ref_idx ...
    )
    p = ...
        p(:);
    sensor_indices = ...
        1:size(sensors,1);
    sensor_indices(ref_idx) = [];
    ref_position = ...
        sensors(ref_idx,:).';
    ref_distance = ...
        norm( ...
            p ...
            - ref_position ...
        );
    residual = ...
        zeros( ...
            numel(sensor_indices), ...
            1 ...
        );
    for n = 1:numel(sensor_indices)
        i = ...
            sensor_indices(n);
        sensor_position = ...
            sensors(i,:).';
        sensor_distance = ...
            norm( ...
                p ...
                - sensor_position ...
            );
        residual(n) = ...
            sensor_distance ...
            - ref_distance ...
            - rho(n);
    end
end

function estimated_rho = ...
    calculate_tdoa_distance_difference( ...
        p, ...
        sensors, ...
        ref_idx ...
    )
    p = ...
        p(:);
    sensor_indices = ...
        1:size(sensors,1);
    sensor_indices(ref_idx) = [];
    ref_position = ...
        sensors(ref_idx,:).';
    ref_distance = ...
        norm( ...
            p ...
            - ref_position ...
        );
    estimated_rho = ...
        zeros( ...
            numel(sensor_indices), ...
            1 ...
        );
    for n = 1:numel(sensor_indices)
        i = ...
            sensor_indices(n);
        sensor_position = ...
            sensors(i,:).';
        sensor_distance = ...
            norm( ...
                p ...
                - sensor_position ...
            );
        estimated_rho(n) = ...
            sensor_distance ...
            - ref_distance;
    end
end


